[package]
name = "zigalloc"
description = "Zig allocator for Rust projects"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
libc = "0.2"
